#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 	0
bspc config window_gap		0

bspc config split_ratio 	0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a blender desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# random wallpaper from ~/wallpapers
wallpapers=(`ls $HOME/wallpapers/*`)
wallpaperslen=0
for f in ${wallpapers[*]}; do
	wallpaperslen=$((wallpaperslen + 1))
done

feh --bg-fill ${wallpapers[`shuf -i 0-$((wallpaperslen - 1)) -n 1`]}
